name: Saucedemo UI tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choise target
        required: true
        default: all test
        type: choise
        options:
          - all test
          - second test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-versions: "3.10"
      - name: Setup Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: all test
        if: "github.event.inputs.deploiment_target == 'All test'"
        run: pytest
      - name: second test
        if: "github.event.inputs.deploiment_target == 'second test'"
        run: pytest